version: '3.9'

services:
  db:
    image: postgres:15
    container_name: rif_postgres
    restart: always
    environment:
      POSTGRES_DB: mutants
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis:7
    container_name: rif_redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata:
